### ISSUE TITLE
"Too many requests" HTTP error when using journey method

### ISSUE THREAD

**Issue by whiver** [juliuste/sncf#13]
Hi,
I sometimes (even often) get the 429 "Too many requests" error when using the `journey` method:

```
error:  HTTPError: Response code 429 (None)
    at stream.catch.then.data (/app/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It occurs at least with these parameters:
- departure: `FRLPD`
- arrival: `FRPLY`
- duration: 2h
- date: apparently every day repro, but in my case 2018-06-04

I suppose that it is due to the several queries needed to get a full result in this time range.
Can you repro it?

Thanks,

William

**Comment by juliuste** [comment]
Hi, 
yes, I can reproduce it. This also occured when I first started writing the module, I always thought this had happened because I sent way too many requests while debugging the code. I'm going to have a second look at it now. Thank you for letting me know 🙂

**Comment by derhuerst** [comment]
Have do double-checked that there are no HTTP headers indicating the limits?

**Comment by whiver** [comment]
I didn't find anything in the headers sent by the browser on the Oui.sncf website, except a strange one:

```
X-VSD-SMART-GUY-GUARD: O|rqWSdulT3739534;T4QQRZC\
```
I'm wondering what the purpose of this header is... I doesn't change between requests, I'll try to see if adding this header changes anything.

Otherwise maybe the server checks for a specific cookie to enable or disable the rate restriction.

**Comment by derhuerst** [comment]
> I didn't find anything in the headers sent by the browser on the Oui.sncf website, except a strange one:

What about those sent by the server?

**Comment by whiver** [comment]
Nothing special. Though I think that the potential information about rate limits would more likely be in the response body, but strangely, I cannot manage to reproduce the error using Postman...

**Comment by whiver** [comment]
I tried today using another server and the error doesn't happen again. I was previously using a Heroku hosting, so there is likely someone on the same IP than me performing a lot of requests on the API.

As it seems "resolved" (even if there might be something to do with the headers), feel free to close the issue if you want.

**Comment by derhuerst** [comment]
I think a solution would be to find the limits and let the `sncf` package support throttling.

**Comment by whiver** [comment]
I was able to repro the bug yesterday: I performed several requests in a short amount of time and since this time I get the 429 Too Many Requests error. So I can confirm there is no "Retry-After" header.

**Comment by derhuerst** [comment]
Do you know how many requests you have sent? From you gut feeling, what was the period of time you got locked out after?

**Comment by derhuerst** [comment]
Usually, there are three variables involved in rate-limiting:

- The amount of time the rate-limiting will be applied to.
- The nr of requests you can send in this time.
- The amount of time you will be blocked for.

As an example: If i query site X more than 200 times in 10 minutes, I will get blocked for 60 minutes.

Sometimes, there are multiple of these rules in effect.

We would have to figure those out for SNCF in order to build reliable throttling.

**Comment by cedced19** [comment]
I had the same issue today I cannot perform request since 12:00 am after doing like 30 request.

**Comment by whiver** [comment]
If you find a way to mitigate the issue please tell me, I'm still interested.

**Comment by cedced19** [comment]
I'm blocked since a week now, I'll do something to hide my ip behind proxy or something so. Do you have any idea of how much time I'll be blocked ?

**Comment by whiver** [comment]
No sorry :/ And the fact is that hiding your IP behind another will not solve the problem, except if you continuously change your IP address, which is not a viable solution. We definitely need to find a way not to be considered as a bot. I tried to set a custom User Agent string but it doesn't work.
If you also use your blocked IP as a VPN, note that you can use it to access the Oui.sncf website, then you will just have to answer the shown captcha to temporary unblock your server IP.
